
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/created-by: kubesphere.io/{{ include "openpitrix.name" .}}-apiserver
  labels:
    app: openpitrix-apiserver
  name: {{ include "openpitrix.name" . }}-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: openpitrix-apiserver
  type: ClusterIP
